/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    posts: Post;
    media: Media;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  slug?: string | null;
  /**
   * Upload a featured image for this blog post
   */
  featuredImage?: (string | null) | Media;
  /**
   * Brief summary of the blog post content
   */
  excerpt: string;
  layout?:
    | (
        | {
            /**
             * Choose font family for this text block
             */
            fontFamily?:
              | (
                  | 'default'
                  | 'times-new-roman'
                  | 'arial'
                  | 'georgia'
                  | 'verdana'
                  | 'calibri'
                  | 'garamond'
                  | 'helvetica'
                  | 'courier-new'
                  | 'trebuchet-ms'
                  | 'brush-script'
                )
              | null;
            /**
             * Choose font size
             */
            fontSize?: ('small' | 'normal' | 'large' | 'xlarge') | null;
            /**
             * Choose text color
             */
            textColor?: ('default' | 'primary' | 'dark' | 'light' | 'success' | 'warning' | 'error') | null;
            /**
             * Main content with formatting options
             */
            content: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            language?:
              | (
                  | 'javascript'
                  | 'typescript'
                  | 'python'
                  | 'html'
                  | 'css'
                  | 'json'
                  | 'bash'
                  | 'java'
                  | 'php'
                  | 'sql'
                  | 'text'
                )
              | null;
            /**
             * Enter your code here
             */
            code: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'code';
          }
        | {
            /**
             * Optional table title
             */
            tableTitle?: string | null;
            headerStyle?: {
              backgroundColor?:
                | ('#3B82F6' | '#10B981' | '#EF4444' | '#8B5CF6' | '#F59E0B' | '#6B7280' | '#14B8A6')
                | null;
              textColor?: ('#FFFFFF' | '#000000') | null;
            };
            /**
             * Table column headers
             */
            headers?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            /**
             * Add table rows - ensure each row has same number of cells as headers
             */
            rows?:
              | {
                  cells?:
                    | {
                        content: string;
                        /**
                         * Highlight this cell
                         */
                        highlight?: boolean | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            borderStyle?: ('all' | 'horizontal' | 'header' | 'none') | null;
            /**
             * Alternate row background colors for better readability
             */
            stripedRows?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTable';
          }
        | {
            title: string;
            columns?:
              | {
                  columnTitle: string;
                  cards?:
                    | {
                        title: string;
                        description?: string | null;
                        status?: ('todo' | 'in-progress' | 'done') | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'kanbanBoard';
          }
        | {
            title?: string | null;
            items?:
              | {
                  timeframe: string;
                  title: string;
                  description?: string | null;
                  actions?:
                    | {
                        action?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            emoji?: string | null;
            text: {
              root: {
                type: string;
                children: {
                  type: string;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            color?: ('gray' | 'yellow' | 'blue' | 'green' | 'red') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            type?: ('line' | 'dashed') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
      )[]
    | null;
  author?: (string | null) | User;
  publishedDate?: string | null;
  status?: ('draft' | 'published') | null;
  tags?:
    | (
        | 'cmc-regulatory'
        | 'mhra'
        | 'pharmaceutical'
        | 'validation'
        | 'quality-control'
        | 'manufacturing'
        | 'api'
        | 'specification'
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  featuredImage?: T;
  excerpt?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              fontFamily?: T;
              fontSize?: T;
              textColor?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        code?:
          | T
          | {
              language?: T;
              code?: T;
              id?: T;
              blockName?: T;
            };
        richTable?:
          | T
          | {
              tableTitle?: T;
              headerStyle?:
                | T
                | {
                    backgroundColor?: T;
                    textColor?: T;
                  };
              headers?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              rows?:
                | T
                | {
                    cells?:
                      | T
                      | {
                          content?: T;
                          highlight?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              borderStyle?: T;
              stripedRows?: T;
              id?: T;
              blockName?: T;
            };
        kanbanBoard?:
          | T
          | {
              title?: T;
              columns?:
                | T
                | {
                    columnTitle?: T;
                    cards?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          status?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    timeframe?: T;
                    title?: T;
                    description?: T;
                    actions?:
                      | T
                      | {
                          action?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              emoji?: T;
              text?: T;
              color?: T;
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              type?: T;
              id?: T;
              blockName?: T;
            };
      };
  author?: T;
  publishedDate?: T;
  status?: T;
  tags?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}